Define SHT_ANDROID_RELR to process Android kernel
It fails to process a recent Android's Generic Kernel Image due to
undefined SH_TYPE:

```
ValueError: 1879047936 is not a valid SH_TYPE
```

This commit adds the SHT_ANDROID_RELR to fix this issue. The code
originates the LLVM code.

https://github.com/llvm/llvm-project/blob/a21521a4efacba405964767a8c2280b40aa68536/llvm/include/llvm/BinaryFormat/ELF.h#L1191

Signed-off-by: Akira Moroo <akiram@ricsec.co.jp>